echo "======================= REDIS ==========================="
echo "Now set redis to start at reboot"
echo "@reboot /usr/local/bin/redis-server /home/vagrant/install/redis/redis-5.0.5/redis.conf"
echo "Copy redis.conf configured right"
echo "/usr/local/bin/redis-server /home/vagrant/redis/redis-5.0.5/redis/redis-5.0.5/redis.conf"
echo "========================================================="
echo "Install gems"
echo "Copy secret key"
echo "Install Yarn packages"
echo "************************ SIDEKIQ ************************"
echo "Setup sidekiq"
echo "1-) Modify sidekiq.service lines with app location"
echo "  WorkingDirectory=/opt/fish-module-genomico"
echo "  ExecStart=/bin/bash -lc 'exec /home/vagrant/.rbenv/shims/bundle exec sidekiq -e production'"
echo "2-)Change lines to user"
echo "  User=vagrant"
echo "  Group=vagrant"
echo "3-) Copy sidekiq.service to /lib/systemd/system"
echo "run systemctl enable sidekiq"
echo "systemctl start sidekiq"
echo "***********************************************************"
echo "setup postgres production user"
echo "sudo -u postgres psql"
echo "ALTER USER postgres PASSWORD 'password';"
echo "export RAILS_ENV=production to .bashrc"
